@url = http://localhost:3000/v1
# @url = https://toxin-api.js-dev.su/v1
@accessToken = {{refresh.response.body.$.data.accessToken}}

###
# @name register
POST {{url}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "birthday": "2002-04-10",
    "email": "naumenkokirill466@gmail.com",
    "gender": "male",
    "isSubscriber": "false",
    "lastName": "efwfsdf",
    "name": "John",
    "password": "Qwerty123"
}
###

###
# @name login
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "naumenkokirill466@gmail.com",
  "password": "Qwerty123"
}
###

###
# @name loginAdmin
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "Qwerty123"
}
###

###
# @name Logout
GET {{url}}/auth/logout
Accept: application/json
###

###
# @name refresh
GET {{url}}/auth/refresh
Accept: application/json
###

###
# @name getUsers
GET {{url}}/users
    # ?select=gender
    ?birthday=2002-04-10
    # ?sort=-createdAt
    # &page=1010
Accept: application/json
Authorization: Bearer {{accessToken}}
###

###
# @name getSingleUser
GET {{url}}/users/65
Accept: application/json
###


###
# @name confirmEmail
GET {{url}}/email/confirm/{{code}}
Accept: application/json
Authorization: Bearer {{accessToken}}
###
@code = aba279a792c839c6009419265c9a86dfb32c289ba09f087469a8554877d83c34
###

###
# @name updateEmail
POST {{url}}/email
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "newEmail": "naumenkokirill466+test@gmail.com"
}
###

###
# @name restoreEmail
GET {{url}}/email/restore/{{restoreCode}}
Accept: application/json
Authorization: Bearer {{accessToken}}
###
@restoreCode = 67d14c46b3b991f618c012a55262dc6422f1cbec39cf9658b9730b90881ba237
###

# @name accountAvatar
POST {{url}}/account/avatar
Accept: application/json
Content-Type: multipart/form-data; boundary=-------------573cf973d5228
-------------573cf973d5228
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< ./avatar.png
-------------573cf973d5228--