db:
  mongo:
    host: 'mongo'
    port: 27017
    database: 'toxin'
    replicaSet: 'rsDev'

  redis:
    host: 'redis'
    port: 6379
    database: ''
    user: ''
    password: 'qwerty'

security:
  passwordHashRounds: 12
  tokens:
    accessExpTime: 300
    refreshExpTime: 5097600
    accessSecret: 'super-secret-jwt-access-token'
  cookieSecret: 'super-secret-cookie-sign'
  secureCookie: false
  deletedUserTtl: 15_552_000
  emailConfirmationTime: 600

adminAccount:
  email: 'admin@admin.com'
  password: 'Qwerty123'

requests:
  cacheTtl: 15
  throttle: 5
  limit: 4

mail:
  host: 'smtp.timeweb.ru'
  port: 25
  user: 'toxin@js-dev.su'
  password: '9ju527o0s2'
  secure: false
  name: 'Toxin Support'
  baseUrl: 'http://localhost:3000'
  confirmEmailUrl: 'v1/emailConfirmation'
  resetPasswordUrl: 'v1/resetPassword'
