version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toxin-nest
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017/toxin
      REDIS_CONNECTION_STRING: redis://:qwerty@cache:6379
      PASSWORD_HASH_ROUNDS: 12
      NODE_ENV: development
      TZ: UTC
      JWT_ACCESS_EXP_TIME: 300
      JWT_ACCESS_SECRET: super-secret-jwt-access-token
      JWT_REFRESH_EXP_TIME: 5097600
      COOKIE_SECRET: super-secret-cookie-sign
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: Qwerty123
      CACHE_TTL: 15
  db:
    image: mongo:7.0
    container_name: toxin-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  cache:
    image: redis:7.2
    container_name: toxin-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass qwerty
  s3:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: toxin
      MINIO_ROOT_PASSWORD: qwerty123
    volumes:
      - ./data/files:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
