version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toxin-nest
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017/toxin
      NODE_ENV: development
      TZ: UTC
  db:
    image: mongo:7.0
    attach: false
    container_name: toxin-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
