version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toxin-nest
    ports:
      - '3000:3000'
      - '25:25'
    command:
      - npm
      - run
      - start:dev
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      CONFIG_PATH: ./config.yaml
      NODE_ENV: development
      TZ: UTC
  mongo:
    image: mongo:7.0
    container_name: toxin-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    command: ['--replSet', 'rsDev', '--bind_ip_all']
  mongoinit:
    image: mongo:7.0
    restart: 'no'
    depends_on:
      - mongo
    command: >
      mongosh --host mongo:27017 --eval 'rs.initiate();'
  redis:
    image: redis:7.2
    container_name: toxin-redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass qwerty
  s3:
    image: minio/minio:latest
    container_name: toxin-s3
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data/
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: toxin
      MINIO_ROOT_PASSWORD: qwerty123
      MINIO_REGION: ru-west-1
    volumes:
      - ./data/files:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
