name: Lint Code

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        env:
          HUSKY: 0
        with:
          auto_fix: true
          eslint: true
          prettier: true
          eslint_extensions: js,ts,tsx
          prettier_extensions: js,ts,tsx
          eslint_dir: src/
          eslint_args: '-c ../.eslintrc.js'
          prettier_dir: src/
          commit_message: 'refactor: 💅Fix code style issues with ${linter}'
